def draw_power_plant():
    print("    (  )         ( )  ( )  ( )")
    print("   (    )       ( )  ( )  ( )")
    print("  (      )     ( )  ( )  ( )")
    print(" (        )   ( )  ( )  ( )")
    print("\          /  | |  | |  | |   ")
    print(" \        /   | |  | |  | |   ")
    print("  \      /    | |  | |  | |   ")
    print("  /      \    | |  | |  | |   ")
    print(" /        \   | |  | |  | |   ")
    print("/__________\__|_|__|_|__|_|___")
    print("|                            |")
    print("|                            |")
    print("|     _                      |")
    print("|    | |                     |") 
    return
